# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: udpa/annotations/migrate.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'udpa/annotations/migrate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eudpa/annotations/migrate.proto\x12\x10udpa.annotations\x1a google/protobuf/descriptor.proto\"+\n\x11MigrateAnnotation\x12\x16\n\x06rename\x18\x01 \x01(\tR\x06rename\"Y\n\x16\x46ieldMigrateAnnotation\x12\x16\n\x06rename\x18\x01 \x01(\tR\x06rename\x12\'\n\x0foneof_promotion\x18\x02 \x01(\tR\x0eoneofPromotion\"?\n\x15\x46ileMigrateAnnotation\x12&\n\x0fmove_to_package\x18\x02 \x01(\tR\rmoveToPackage:p\n\x0fmessage_migrate\x12\x1f.google.protobuf.MessageOptions\x18\x8e\xe3\xffQ \x01(\x0b\x32#.udpa.annotations.MigrateAnnotationR\x0emessageMigrate:o\n\rfield_migrate\x12\x1d.google.protobuf.FieldOptions\x18\x8e\xe3\xffQ \x01(\x0b\x32(.udpa.annotations.FieldMigrateAnnotationR\x0c\x66ieldMigrate:g\n\x0c\x65num_migrate\x12\x1c.google.protobuf.EnumOptions\x18\x8e\xe3\xffQ \x01(\x0b\x32#.udpa.annotations.MigrateAnnotationR\x0b\x65numMigrate:w\n\x12\x65num_value_migrate\x12!.google.protobuf.EnumValueOptions\x18\x8e\xe3\xffQ \x01(\x0b\x32#.udpa.annotations.MigrateAnnotationR\x10\x65numValueMigrate:k\n\x0c\x66ile_migrate\x12\x1c.google.protobuf.FileOptions\x18\x8e\xe3\xffQ \x01(\x0b\x32\'.udpa.annotations.FileMigrateAnnotationR\x0b\x66ileMigrateB)Z\'github.com/cncf/xds/go/udpa/annotationsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udpa.annotations.migrate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/cncf/xds/go/udpa/annotations'
  _globals['_MIGRATEANNOTATION']._serialized_start=86
  _globals['_MIGRATEANNOTATION']._serialized_end=129
  _globals['_FIELDMIGRATEANNOTATION']._serialized_start=131
  _globals['_FIELDMIGRATEANNOTATION']._serialized_end=220
  _globals['_FILEMIGRATEANNOTATION']._serialized_start=222
  _globals['_FILEMIGRATEANNOTATION']._serialized_end=285
# @@protoc_insertion_point(module_scope)
