// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xds/annotations/v3/status.proto

package xds_annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageStatusAnnotation struct {
	WorkInProgress       bool     `protobuf:"varint,1,opt,name=work_in_progress,json=workInProgress,proto3" json:"work_in_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageStatusAnnotation) Reset()         { *m = MessageStatusAnnotation{} }
func (m *MessageStatusAnnotation) String() string { return proto.CompactTextString(m) }
func (*MessageStatusAnnotation) ProtoMessage()    {}
func (*MessageStatusAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb5d31100819305f, []int{0}
}

func (m *MessageStatusAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageStatusAnnotation.Unmarshal(m, b)
}
func (m *MessageStatusAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageStatusAnnotation.Marshal(b, m, deterministic)
}
func (m *MessageStatusAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageStatusAnnotation.Merge(m, src)
}
func (m *MessageStatusAnnotation) XXX_Size() int {
	return xxx_messageInfo_MessageStatusAnnotation.Size(m)
}
func (m *MessageStatusAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageStatusAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_MessageStatusAnnotation proto.InternalMessageInfo

func (m *MessageStatusAnnotation) GetWorkInProgress() bool {
	if m != nil {
		return m.WorkInProgress
	}
	return false
}

type FieldStatusAnnotation struct {
	WorkInProgress       bool     `protobuf:"varint,1,opt,name=work_in_progress,json=workInProgress,proto3" json:"work_in_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldStatusAnnotation) Reset()         { *m = FieldStatusAnnotation{} }
func (m *FieldStatusAnnotation) String() string { return proto.CompactTextString(m) }
func (*FieldStatusAnnotation) ProtoMessage()    {}
func (*FieldStatusAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb5d31100819305f, []int{1}
}

func (m *FieldStatusAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldStatusAnnotation.Unmarshal(m, b)
}
func (m *FieldStatusAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldStatusAnnotation.Marshal(b, m, deterministic)
}
func (m *FieldStatusAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldStatusAnnotation.Merge(m, src)
}
func (m *FieldStatusAnnotation) XXX_Size() int {
	return xxx_messageInfo_FieldStatusAnnotation.Size(m)
}
func (m *FieldStatusAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldStatusAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_FieldStatusAnnotation proto.InternalMessageInfo

func (m *FieldStatusAnnotation) GetWorkInProgress() bool {
	if m != nil {
		return m.WorkInProgress
	}
	return false
}

var E_MessageStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageStatusAnnotation)(nil),
	Field:         222707719,
	Name:          "xds.annotations.message_status",
	Tag:           "bytes,222707719,opt,name=message_status",
	Filename:      "xds/annotations/v3/status.proto",
}

var E_FieldStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldStatusAnnotation)(nil),
	Field:         222707719,
	Name:          "xds.annotations.field_status",
	Tag:           "bytes,222707719,opt,name=field_status",
	Filename:      "xds/annotations/v3/status.proto",
}

func init() {
	proto.RegisterType((*MessageStatusAnnotation)(nil), "xds.annotations.MessageStatusAnnotation")
	proto.RegisterType((*FieldStatusAnnotation)(nil), "xds.annotations.FieldStatusAnnotation")
	proto.RegisterExtension(E_MessageStatus)
	proto.RegisterExtension(E_FieldStatus)
}

func init() { proto.RegisterFile("xds/annotations/v3/status.proto", fileDescriptor_fb5d31100819305f) }

var fileDescriptor_fb5d31100819305f = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xaf, 0x48, 0x29, 0xd6,
	0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2f, 0x33, 0xd6, 0x2f,
	0x2e, 0x49, 0x2c, 0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xaf, 0x48, 0x29,
	0xd6, 0x43, 0x52, 0x20, 0xa5, 0x90, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x0f, 0x96, 0x4e, 0x2a,
	0x4d, 0xd3, 0x4f, 0x49, 0x2d, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xc9, 0x2f, 0x82, 0x68, 0x51, 0x72,
	0xe6, 0x12, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d, 0x06, 0x9b, 0xe4, 0x08, 0xd7, 0x2d,
	0xa4, 0xc1, 0x25, 0x50, 0x9e, 0x5f, 0x94, 0x1d, 0x9f, 0x99, 0x17, 0x5f, 0x50, 0x94, 0x9f, 0x5e,
	0x94, 0x5a, 0x5c, 0x2c, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x11, 0xc4, 0x07, 0x12, 0xf7, 0xcc, 0x0b,
	0x80, 0x8a, 0x2a, 0x39, 0x72, 0x89, 0xba, 0x65, 0xa6, 0xe6, 0xa4, 0x90, 0x6f, 0x84, 0x55, 0x31,
	0x17, 0x5f, 0x2e, 0xc4, 0x1d, 0xf1, 0x10, 0x2f, 0x09, 0xc9, 0xeb, 0x41, 0x1c, 0xaf, 0x07, 0x73,
	0xbc, 0x1e, 0xd4, 0xa1, 0xfe, 0x05, 0x60, 0xcf, 0x49, 0xb4, 0x37, 0xcc, 0xcc, 0x52, 0x60, 0xd4,
	0xe0, 0x36, 0xd2, 0xd0, 0x43, 0xf3, 0xb7, 0x1e, 0x0e, 0x2f, 0x05, 0xf1, 0xe6, 0x22, 0x4b, 0x58,
	0x65, 0x73, 0xf1, 0xa4, 0x81, 0xdc, 0x0d, 0xb3, 0x52, 0x16, 0xc3, 0x4a, 0xb0, 0xb7, 0x30, 0x2c,
	0x54, 0xc3, 0xb0, 0x10, 0xab, 0xf7, 0x83, 0xb8, 0xd3, 0x10, 0xc2, 0x49, 0x6c, 0x60, 0x43, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x08, 0xa6, 0xd7, 0x93, 0xc6, 0x01, 0x00, 0x00,
}
