# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xds/annotations/v3/status.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'xds/annotations/v3/status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fxds/annotations/v3/status.proto\x12\x12xds.annotations.v3\x1a google/protobuf/descriptor.proto\"@\n\x14\x46ileStatusAnnotation\x12(\n\x10work_in_progress\x18\x01 \x01(\x08R\x0eworkInProgress\"C\n\x17MessageStatusAnnotation\x12(\n\x10work_in_progress\x18\x01 \x01(\x08R\x0eworkInProgress\"A\n\x15\x46ieldStatusAnnotation\x12(\n\x10work_in_progress\x18\x01 \x01(\x08R\x0eworkInProgress\"\x9c\x01\n\x10StatusAnnotation\x12(\n\x10work_in_progress\x18\x01 \x01(\x08R\x0eworkInProgress\x12^\n\x16package_version_status\x18\x02 \x01(\x0e\x32(.xds.annotations.v3.PackageVersionStatusR\x14packageVersionStatus*]\n\x14PackageVersionStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x46ROZEN\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x12 \n\x1cNEXT_MAJOR_VERSION_CANDIDATE\x10\x03:j\n\x0b\x66ile_status\x12\x1c.google.protobuf.FileOptions\x18\xea\xc8\x94l \x01(\x0b\x32(.xds.annotations.v3.FileStatusAnnotationR\nfileStatus:v\n\x0emessage_status\x12\x1f.google.protobuf.MessageOptions\x18\xea\xc8\x94l \x01(\x0b\x32+.xds.annotations.v3.MessageStatusAnnotationR\rmessageStatus:n\n\x0c\x66ield_status\x12\x1d.google.protobuf.FieldOptions\x18\xea\xc8\x94l \x01(\x0b\x32).xds.annotations.v3.FieldStatusAnnotationR\x0b\x66ieldStatusB+Z)github.com/cncf/xds/go/xds/annotations/v3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xds.annotations.v3.status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/cncf/xds/go/xds/annotations/v3'
  _globals['_PACKAGEVERSIONSTATUS']._serialized_start=450
  _globals['_PACKAGEVERSIONSTATUS']._serialized_end=543
  _globals['_FILESTATUSANNOTATION']._serialized_start=89
  _globals['_FILESTATUSANNOTATION']._serialized_end=153
  _globals['_MESSAGESTATUSANNOTATION']._serialized_start=155
  _globals['_MESSAGESTATUSANNOTATION']._serialized_end=222
  _globals['_FIELDSTATUSANNOTATION']._serialized_start=224
  _globals['_FIELDSTATUSANNOTATION']._serialized_end=289
  _globals['_STATUSANNOTATION']._serialized_start=292
  _globals['_STATUSANNOTATION']._serialized_end=448
# @@protoc_insertion_point(module_scope)
