// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xds/type/matcher/v3/matcher.proto

package xds_type_matcher_v3

import (
	fmt "fmt"
	_ "github.com/cncf/xds/go/xds/annotations/v3"
	v3 "github.com/cncf/xds/go/xds/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Matcher struct {
	// Types that are valid to be assigned to MatcherType:
	//	*Matcher_MatcherList_
	//	*Matcher_MatcherTree_
	MatcherType          isMatcher_MatcherType `protobuf_oneof:"matcher_type"`
	OnNoMatch            *Matcher_OnMatch      `protobuf:"bytes,3,opt,name=on_no_match,json=onNoMatch,proto3" json:"on_no_match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Matcher) Reset()         { *m = Matcher{} }
func (m *Matcher) String() string { return proto.CompactTextString(m) }
func (*Matcher) ProtoMessage()    {}
func (*Matcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0}
}

func (m *Matcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher.Unmarshal(m, b)
}
func (m *Matcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher.Marshal(b, m, deterministic)
}
func (m *Matcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher.Merge(m, src)
}
func (m *Matcher) XXX_Size() int {
	return xxx_messageInfo_Matcher.Size(m)
}
func (m *Matcher) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher proto.InternalMessageInfo

type isMatcher_MatcherType interface {
	isMatcher_MatcherType()
}

type Matcher_MatcherList_ struct {
	MatcherList *Matcher_MatcherList `protobuf:"bytes,1,opt,name=matcher_list,json=matcherList,proto3,oneof"`
}

type Matcher_MatcherTree_ struct {
	MatcherTree *Matcher_MatcherTree `protobuf:"bytes,2,opt,name=matcher_tree,json=matcherTree,proto3,oneof"`
}

func (*Matcher_MatcherList_) isMatcher_MatcherType() {}

func (*Matcher_MatcherTree_) isMatcher_MatcherType() {}

func (m *Matcher) GetMatcherType() isMatcher_MatcherType {
	if m != nil {
		return m.MatcherType
	}
	return nil
}

func (m *Matcher) GetMatcherList() *Matcher_MatcherList {
	if x, ok := m.GetMatcherType().(*Matcher_MatcherList_); ok {
		return x.MatcherList
	}
	return nil
}

func (m *Matcher) GetMatcherTree() *Matcher_MatcherTree {
	if x, ok := m.GetMatcherType().(*Matcher_MatcherTree_); ok {
		return x.MatcherTree
	}
	return nil
}

func (m *Matcher) GetOnNoMatch() *Matcher_OnMatch {
	if m != nil {
		return m.OnNoMatch
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Matcher) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Matcher_MatcherList_)(nil),
		(*Matcher_MatcherTree_)(nil),
	}
}

type Matcher_OnMatch struct {
	// Types that are valid to be assigned to OnMatch:
	//	*Matcher_OnMatch_Matcher
	//	*Matcher_OnMatch_Action
	OnMatch              isMatcher_OnMatch_OnMatch `protobuf_oneof:"on_match"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Matcher_OnMatch) Reset()         { *m = Matcher_OnMatch{} }
func (m *Matcher_OnMatch) String() string { return proto.CompactTextString(m) }
func (*Matcher_OnMatch) ProtoMessage()    {}
func (*Matcher_OnMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 0}
}

func (m *Matcher_OnMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_OnMatch.Unmarshal(m, b)
}
func (m *Matcher_OnMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_OnMatch.Marshal(b, m, deterministic)
}
func (m *Matcher_OnMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_OnMatch.Merge(m, src)
}
func (m *Matcher_OnMatch) XXX_Size() int {
	return xxx_messageInfo_Matcher_OnMatch.Size(m)
}
func (m *Matcher_OnMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_OnMatch.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_OnMatch proto.InternalMessageInfo

type isMatcher_OnMatch_OnMatch interface {
	isMatcher_OnMatch_OnMatch()
}

type Matcher_OnMatch_Matcher struct {
	Matcher *Matcher `protobuf:"bytes,1,opt,name=matcher,proto3,oneof"`
}

type Matcher_OnMatch_Action struct {
	Action *v3.TypedExtensionConfig `protobuf:"bytes,2,opt,name=action,proto3,oneof"`
}

func (*Matcher_OnMatch_Matcher) isMatcher_OnMatch_OnMatch() {}

func (*Matcher_OnMatch_Action) isMatcher_OnMatch_OnMatch() {}

func (m *Matcher_OnMatch) GetOnMatch() isMatcher_OnMatch_OnMatch {
	if m != nil {
		return m.OnMatch
	}
	return nil
}

func (m *Matcher_OnMatch) GetMatcher() *Matcher {
	if x, ok := m.GetOnMatch().(*Matcher_OnMatch_Matcher); ok {
		return x.Matcher
	}
	return nil
}

func (m *Matcher_OnMatch) GetAction() *v3.TypedExtensionConfig {
	if x, ok := m.GetOnMatch().(*Matcher_OnMatch_Action); ok {
		return x.Action
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Matcher_OnMatch) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Matcher_OnMatch_Matcher)(nil),
		(*Matcher_OnMatch_Action)(nil),
	}
}

type Matcher_MatcherList struct {
	Matchers             []*Matcher_MatcherList_FieldMatcher `protobuf:"bytes,1,rep,name=matchers,proto3" json:"matchers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Matcher_MatcherList) Reset()         { *m = Matcher_MatcherList{} }
func (m *Matcher_MatcherList) String() string { return proto.CompactTextString(m) }
func (*Matcher_MatcherList) ProtoMessage()    {}
func (*Matcher_MatcherList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 1}
}

func (m *Matcher_MatcherList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_MatcherList.Unmarshal(m, b)
}
func (m *Matcher_MatcherList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_MatcherList.Marshal(b, m, deterministic)
}
func (m *Matcher_MatcherList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_MatcherList.Merge(m, src)
}
func (m *Matcher_MatcherList) XXX_Size() int {
	return xxx_messageInfo_Matcher_MatcherList.Size(m)
}
func (m *Matcher_MatcherList) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_MatcherList.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_MatcherList proto.InternalMessageInfo

func (m *Matcher_MatcherList) GetMatchers() []*Matcher_MatcherList_FieldMatcher {
	if m != nil {
		return m.Matchers
	}
	return nil
}

type Matcher_MatcherList_Predicate struct {
	// Types that are valid to be assigned to MatchType:
	//	*Matcher_MatcherList_Predicate_SinglePredicate_
	//	*Matcher_MatcherList_Predicate_OrMatcher
	//	*Matcher_MatcherList_Predicate_AndMatcher
	//	*Matcher_MatcherList_Predicate_NotMatcher
	MatchType            isMatcher_MatcherList_Predicate_MatchType `protobuf_oneof:"match_type"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Matcher_MatcherList_Predicate) Reset()         { *m = Matcher_MatcherList_Predicate{} }
func (m *Matcher_MatcherList_Predicate) String() string { return proto.CompactTextString(m) }
func (*Matcher_MatcherList_Predicate) ProtoMessage()    {}
func (*Matcher_MatcherList_Predicate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 1, 0}
}

func (m *Matcher_MatcherList_Predicate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_MatcherList_Predicate.Unmarshal(m, b)
}
func (m *Matcher_MatcherList_Predicate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_MatcherList_Predicate.Marshal(b, m, deterministic)
}
func (m *Matcher_MatcherList_Predicate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_MatcherList_Predicate.Merge(m, src)
}
func (m *Matcher_MatcherList_Predicate) XXX_Size() int {
	return xxx_messageInfo_Matcher_MatcherList_Predicate.Size(m)
}
func (m *Matcher_MatcherList_Predicate) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_MatcherList_Predicate.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_MatcherList_Predicate proto.InternalMessageInfo

type isMatcher_MatcherList_Predicate_MatchType interface {
	isMatcher_MatcherList_Predicate_MatchType()
}

type Matcher_MatcherList_Predicate_SinglePredicate_ struct {
	SinglePredicate *Matcher_MatcherList_Predicate_SinglePredicate `protobuf:"bytes,1,opt,name=single_predicate,json=singlePredicate,proto3,oneof"`
}

type Matcher_MatcherList_Predicate_OrMatcher struct {
	OrMatcher *Matcher_MatcherList_Predicate_PredicateList `protobuf:"bytes,2,opt,name=or_matcher,json=orMatcher,proto3,oneof"`
}

type Matcher_MatcherList_Predicate_AndMatcher struct {
	AndMatcher *Matcher_MatcherList_Predicate_PredicateList `protobuf:"bytes,3,opt,name=and_matcher,json=andMatcher,proto3,oneof"`
}

type Matcher_MatcherList_Predicate_NotMatcher struct {
	NotMatcher *Matcher_MatcherList_Predicate `protobuf:"bytes,4,opt,name=not_matcher,json=notMatcher,proto3,oneof"`
}

func (*Matcher_MatcherList_Predicate_SinglePredicate_) isMatcher_MatcherList_Predicate_MatchType() {}

func (*Matcher_MatcherList_Predicate_OrMatcher) isMatcher_MatcherList_Predicate_MatchType() {}

func (*Matcher_MatcherList_Predicate_AndMatcher) isMatcher_MatcherList_Predicate_MatchType() {}

func (*Matcher_MatcherList_Predicate_NotMatcher) isMatcher_MatcherList_Predicate_MatchType() {}

func (m *Matcher_MatcherList_Predicate) GetMatchType() isMatcher_MatcherList_Predicate_MatchType {
	if m != nil {
		return m.MatchType
	}
	return nil
}

func (m *Matcher_MatcherList_Predicate) GetSinglePredicate() *Matcher_MatcherList_Predicate_SinglePredicate {
	if x, ok := m.GetMatchType().(*Matcher_MatcherList_Predicate_SinglePredicate_); ok {
		return x.SinglePredicate
	}
	return nil
}

func (m *Matcher_MatcherList_Predicate) GetOrMatcher() *Matcher_MatcherList_Predicate_PredicateList {
	if x, ok := m.GetMatchType().(*Matcher_MatcherList_Predicate_OrMatcher); ok {
		return x.OrMatcher
	}
	return nil
}

func (m *Matcher_MatcherList_Predicate) GetAndMatcher() *Matcher_MatcherList_Predicate_PredicateList {
	if x, ok := m.GetMatchType().(*Matcher_MatcherList_Predicate_AndMatcher); ok {
		return x.AndMatcher
	}
	return nil
}

func (m *Matcher_MatcherList_Predicate) GetNotMatcher() *Matcher_MatcherList_Predicate {
	if x, ok := m.GetMatchType().(*Matcher_MatcherList_Predicate_NotMatcher); ok {
		return x.NotMatcher
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Matcher_MatcherList_Predicate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Matcher_MatcherList_Predicate_SinglePredicate_)(nil),
		(*Matcher_MatcherList_Predicate_OrMatcher)(nil),
		(*Matcher_MatcherList_Predicate_AndMatcher)(nil),
		(*Matcher_MatcherList_Predicate_NotMatcher)(nil),
	}
}

type Matcher_MatcherList_Predicate_SinglePredicate struct {
	Input *v3.TypedExtensionConfig `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// Types that are valid to be assigned to Matcher:
	//	*Matcher_MatcherList_Predicate_SinglePredicate_ValueMatch
	//	*Matcher_MatcherList_Predicate_SinglePredicate_CustomMatch
	Matcher              isMatcher_MatcherList_Predicate_SinglePredicate_Matcher `protobuf_oneof:"matcher"`
	XXX_NoUnkeyedLiteral struct{}                                                `json:"-"`
	XXX_unrecognized     []byte                                                  `json:"-"`
	XXX_sizecache        int32                                                   `json:"-"`
}

func (m *Matcher_MatcherList_Predicate_SinglePredicate) Reset() {
	*m = Matcher_MatcherList_Predicate_SinglePredicate{}
}
func (m *Matcher_MatcherList_Predicate_SinglePredicate) String() string {
	return proto.CompactTextString(m)
}
func (*Matcher_MatcherList_Predicate_SinglePredicate) ProtoMessage() {}
func (*Matcher_MatcherList_Predicate_SinglePredicate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 1, 0, 0}
}

func (m *Matcher_MatcherList_Predicate_SinglePredicate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_MatcherList_Predicate_SinglePredicate.Unmarshal(m, b)
}
func (m *Matcher_MatcherList_Predicate_SinglePredicate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_MatcherList_Predicate_SinglePredicate.Marshal(b, m, deterministic)
}
func (m *Matcher_MatcherList_Predicate_SinglePredicate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_MatcherList_Predicate_SinglePredicate.Merge(m, src)
}
func (m *Matcher_MatcherList_Predicate_SinglePredicate) XXX_Size() int {
	return xxx_messageInfo_Matcher_MatcherList_Predicate_SinglePredicate.Size(m)
}
func (m *Matcher_MatcherList_Predicate_SinglePredicate) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_MatcherList_Predicate_SinglePredicate.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_MatcherList_Predicate_SinglePredicate proto.InternalMessageInfo

func (m *Matcher_MatcherList_Predicate_SinglePredicate) GetInput() *v3.TypedExtensionConfig {
	if m != nil {
		return m.Input
	}
	return nil
}

type isMatcher_MatcherList_Predicate_SinglePredicate_Matcher interface {
	isMatcher_MatcherList_Predicate_SinglePredicate_Matcher()
}

type Matcher_MatcherList_Predicate_SinglePredicate_ValueMatch struct {
	ValueMatch *StringMatcher `protobuf:"bytes,2,opt,name=value_match,json=valueMatch,proto3,oneof"`
}

type Matcher_MatcherList_Predicate_SinglePredicate_CustomMatch struct {
	CustomMatch *v3.TypedExtensionConfig `protobuf:"bytes,3,opt,name=custom_match,json=customMatch,proto3,oneof"`
}

func (*Matcher_MatcherList_Predicate_SinglePredicate_ValueMatch) isMatcher_MatcherList_Predicate_SinglePredicate_Matcher() {
}

func (*Matcher_MatcherList_Predicate_SinglePredicate_CustomMatch) isMatcher_MatcherList_Predicate_SinglePredicate_Matcher() {
}

func (m *Matcher_MatcherList_Predicate_SinglePredicate) GetMatcher() isMatcher_MatcherList_Predicate_SinglePredicate_Matcher {
	if m != nil {
		return m.Matcher
	}
	return nil
}

func (m *Matcher_MatcherList_Predicate_SinglePredicate) GetValueMatch() *StringMatcher {
	if x, ok := m.GetMatcher().(*Matcher_MatcherList_Predicate_SinglePredicate_ValueMatch); ok {
		return x.ValueMatch
	}
	return nil
}

func (m *Matcher_MatcherList_Predicate_SinglePredicate) GetCustomMatch() *v3.TypedExtensionConfig {
	if x, ok := m.GetMatcher().(*Matcher_MatcherList_Predicate_SinglePredicate_CustomMatch); ok {
		return x.CustomMatch
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Matcher_MatcherList_Predicate_SinglePredicate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Matcher_MatcherList_Predicate_SinglePredicate_ValueMatch)(nil),
		(*Matcher_MatcherList_Predicate_SinglePredicate_CustomMatch)(nil),
	}
}

type Matcher_MatcherList_Predicate_PredicateList struct {
	Predicate            []*Matcher_MatcherList_Predicate `protobuf:"bytes,1,rep,name=predicate,proto3" json:"predicate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Matcher_MatcherList_Predicate_PredicateList) Reset() {
	*m = Matcher_MatcherList_Predicate_PredicateList{}
}
func (m *Matcher_MatcherList_Predicate_PredicateList) String() string {
	return proto.CompactTextString(m)
}
func (*Matcher_MatcherList_Predicate_PredicateList) ProtoMessage() {}
func (*Matcher_MatcherList_Predicate_PredicateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 1, 0, 1}
}

func (m *Matcher_MatcherList_Predicate_PredicateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_MatcherList_Predicate_PredicateList.Unmarshal(m, b)
}
func (m *Matcher_MatcherList_Predicate_PredicateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_MatcherList_Predicate_PredicateList.Marshal(b, m, deterministic)
}
func (m *Matcher_MatcherList_Predicate_PredicateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_MatcherList_Predicate_PredicateList.Merge(m, src)
}
func (m *Matcher_MatcherList_Predicate_PredicateList) XXX_Size() int {
	return xxx_messageInfo_Matcher_MatcherList_Predicate_PredicateList.Size(m)
}
func (m *Matcher_MatcherList_Predicate_PredicateList) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_MatcherList_Predicate_PredicateList.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_MatcherList_Predicate_PredicateList proto.InternalMessageInfo

func (m *Matcher_MatcherList_Predicate_PredicateList) GetPredicate() []*Matcher_MatcherList_Predicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

type Matcher_MatcherList_FieldMatcher struct {
	Predicate            *Matcher_MatcherList_Predicate `protobuf:"bytes,1,opt,name=predicate,proto3" json:"predicate,omitempty"`
	OnMatch              *Matcher_OnMatch               `protobuf:"bytes,2,opt,name=on_match,json=onMatch,proto3" json:"on_match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Matcher_MatcherList_FieldMatcher) Reset()         { *m = Matcher_MatcherList_FieldMatcher{} }
func (m *Matcher_MatcherList_FieldMatcher) String() string { return proto.CompactTextString(m) }
func (*Matcher_MatcherList_FieldMatcher) ProtoMessage()    {}
func (*Matcher_MatcherList_FieldMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 1, 1}
}

func (m *Matcher_MatcherList_FieldMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_MatcherList_FieldMatcher.Unmarshal(m, b)
}
func (m *Matcher_MatcherList_FieldMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_MatcherList_FieldMatcher.Marshal(b, m, deterministic)
}
func (m *Matcher_MatcherList_FieldMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_MatcherList_FieldMatcher.Merge(m, src)
}
func (m *Matcher_MatcherList_FieldMatcher) XXX_Size() int {
	return xxx_messageInfo_Matcher_MatcherList_FieldMatcher.Size(m)
}
func (m *Matcher_MatcherList_FieldMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_MatcherList_FieldMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_MatcherList_FieldMatcher proto.InternalMessageInfo

func (m *Matcher_MatcherList_FieldMatcher) GetPredicate() *Matcher_MatcherList_Predicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *Matcher_MatcherList_FieldMatcher) GetOnMatch() *Matcher_OnMatch {
	if m != nil {
		return m.OnMatch
	}
	return nil
}

type Matcher_MatcherTree struct {
	Input *v3.TypedExtensionConfig `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// Types that are valid to be assigned to TreeType:
	//	*Matcher_MatcherTree_ExactMatchMap
	//	*Matcher_MatcherTree_PrefixMatchMap
	//	*Matcher_MatcherTree_CustomMatch
	TreeType             isMatcher_MatcherTree_TreeType `protobuf_oneof:"tree_type"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Matcher_MatcherTree) Reset()         { *m = Matcher_MatcherTree{} }
func (m *Matcher_MatcherTree) String() string { return proto.CompactTextString(m) }
func (*Matcher_MatcherTree) ProtoMessage()    {}
func (*Matcher_MatcherTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 2}
}

func (m *Matcher_MatcherTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_MatcherTree.Unmarshal(m, b)
}
func (m *Matcher_MatcherTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_MatcherTree.Marshal(b, m, deterministic)
}
func (m *Matcher_MatcherTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_MatcherTree.Merge(m, src)
}
func (m *Matcher_MatcherTree) XXX_Size() int {
	return xxx_messageInfo_Matcher_MatcherTree.Size(m)
}
func (m *Matcher_MatcherTree) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_MatcherTree.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_MatcherTree proto.InternalMessageInfo

func (m *Matcher_MatcherTree) GetInput() *v3.TypedExtensionConfig {
	if m != nil {
		return m.Input
	}
	return nil
}

type isMatcher_MatcherTree_TreeType interface {
	isMatcher_MatcherTree_TreeType()
}

type Matcher_MatcherTree_ExactMatchMap struct {
	ExactMatchMap *Matcher_MatcherTree_MatchMap `protobuf:"bytes,2,opt,name=exact_match_map,json=exactMatchMap,proto3,oneof"`
}

type Matcher_MatcherTree_PrefixMatchMap struct {
	PrefixMatchMap *Matcher_MatcherTree_MatchMap `protobuf:"bytes,3,opt,name=prefix_match_map,json=prefixMatchMap,proto3,oneof"`
}

type Matcher_MatcherTree_CustomMatch struct {
	CustomMatch *v3.TypedExtensionConfig `protobuf:"bytes,4,opt,name=custom_match,json=customMatch,proto3,oneof"`
}

func (*Matcher_MatcherTree_ExactMatchMap) isMatcher_MatcherTree_TreeType() {}

func (*Matcher_MatcherTree_PrefixMatchMap) isMatcher_MatcherTree_TreeType() {}

func (*Matcher_MatcherTree_CustomMatch) isMatcher_MatcherTree_TreeType() {}

func (m *Matcher_MatcherTree) GetTreeType() isMatcher_MatcherTree_TreeType {
	if m != nil {
		return m.TreeType
	}
	return nil
}

func (m *Matcher_MatcherTree) GetExactMatchMap() *Matcher_MatcherTree_MatchMap {
	if x, ok := m.GetTreeType().(*Matcher_MatcherTree_ExactMatchMap); ok {
		return x.ExactMatchMap
	}
	return nil
}

func (m *Matcher_MatcherTree) GetPrefixMatchMap() *Matcher_MatcherTree_MatchMap {
	if x, ok := m.GetTreeType().(*Matcher_MatcherTree_PrefixMatchMap); ok {
		return x.PrefixMatchMap
	}
	return nil
}

func (m *Matcher_MatcherTree) GetCustomMatch() *v3.TypedExtensionConfig {
	if x, ok := m.GetTreeType().(*Matcher_MatcherTree_CustomMatch); ok {
		return x.CustomMatch
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Matcher_MatcherTree) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Matcher_MatcherTree_ExactMatchMap)(nil),
		(*Matcher_MatcherTree_PrefixMatchMap)(nil),
		(*Matcher_MatcherTree_CustomMatch)(nil),
	}
}

type Matcher_MatcherTree_MatchMap struct {
	Map                  map[string]*Matcher_OnMatch `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Matcher_MatcherTree_MatchMap) Reset()         { *m = Matcher_MatcherTree_MatchMap{} }
func (m *Matcher_MatcherTree_MatchMap) String() string { return proto.CompactTextString(m) }
func (*Matcher_MatcherTree_MatchMap) ProtoMessage()    {}
func (*Matcher_MatcherTree_MatchMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_5da8e5cb90406c53, []int{0, 2, 0}
}

func (m *Matcher_MatcherTree_MatchMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matcher_MatcherTree_MatchMap.Unmarshal(m, b)
}
func (m *Matcher_MatcherTree_MatchMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matcher_MatcherTree_MatchMap.Marshal(b, m, deterministic)
}
func (m *Matcher_MatcherTree_MatchMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matcher_MatcherTree_MatchMap.Merge(m, src)
}
func (m *Matcher_MatcherTree_MatchMap) XXX_Size() int {
	return xxx_messageInfo_Matcher_MatcherTree_MatchMap.Size(m)
}
func (m *Matcher_MatcherTree_MatchMap) XXX_DiscardUnknown() {
	xxx_messageInfo_Matcher_MatcherTree_MatchMap.DiscardUnknown(m)
}

var xxx_messageInfo_Matcher_MatcherTree_MatchMap proto.InternalMessageInfo

func (m *Matcher_MatcherTree_MatchMap) GetMap() map[string]*Matcher_OnMatch {
	if m != nil {
		return m.Map
	}
	return nil
}

func init() {
	proto.RegisterType((*Matcher)(nil), "xds.type.matcher.v3.Matcher")
	proto.RegisterType((*Matcher_OnMatch)(nil), "xds.type.matcher.v3.Matcher.OnMatch")
	proto.RegisterType((*Matcher_MatcherList)(nil), "xds.type.matcher.v3.Matcher.MatcherList")
	proto.RegisterType((*Matcher_MatcherList_Predicate)(nil), "xds.type.matcher.v3.Matcher.MatcherList.Predicate")
	proto.RegisterType((*Matcher_MatcherList_Predicate_SinglePredicate)(nil), "xds.type.matcher.v3.Matcher.MatcherList.Predicate.SinglePredicate")
	proto.RegisterType((*Matcher_MatcherList_Predicate_PredicateList)(nil), "xds.type.matcher.v3.Matcher.MatcherList.Predicate.PredicateList")
	proto.RegisterType((*Matcher_MatcherList_FieldMatcher)(nil), "xds.type.matcher.v3.Matcher.MatcherList.FieldMatcher")
	proto.RegisterType((*Matcher_MatcherTree)(nil), "xds.type.matcher.v3.Matcher.MatcherTree")
	proto.RegisterType((*Matcher_MatcherTree_MatchMap)(nil), "xds.type.matcher.v3.Matcher.MatcherTree.MatchMap")
	proto.RegisterMapType((map[string]*Matcher_OnMatch)(nil), "xds.type.matcher.v3.Matcher.MatcherTree.MatchMap.MapEntry")
}

func init() { proto.RegisterFile("xds/type/matcher/v3/matcher.proto", fileDescriptor_5da8e5cb90406c53) }

var fileDescriptor_5da8e5cb90406c53 = []byte{
	// 771 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0xce, 0xc4, 0x6d, 0xe2, 0x1c, 0xa7, 0x4d, 0x98, 0x2e, 0x88, 0x0c, 0x82, 0xb6, 0x62, 0xd1,
	0x95, 0x03, 0xad, 0x90, 0xaa, 0xb0, 0x01, 0x43, 0xab, 0x20, 0x11, 0xa8, 0xdc, 0xc2, 0x82, 0x82,
	0xa2, 0xa9, 0x33, 0x4d, 0xad, 0x26, 0x33, 0x96, 0x3d, 0x89, 0x92, 0x07, 0x60, 0xc3, 0xae, 0x2c,
	0x59, 0xb3, 0xe1, 0x01, 0x60, 0xcd, 0x8a, 0x07, 0xe0, 0x0d, 0x78, 0x86, 0xbb, 0xb9, 0xba, 0xab,
	0xab, 0xf9, 0xb1, 0xe3, 0x56, 0x51, 0x6f, 0x9a, 0xdb, 0x55, 0x8e, 0xcf, 0xcc, 0xf7, 0x7d, 0xe3,
	0x73, 0xbe, 0x33, 0x31, 0xec, 0xcd, 0x06, 0x69, 0x5b, 0xcc, 0x63, 0xda, 0x1e, 0x13, 0x11, 0xde,
	0xd0, 0xa4, 0x3d, 0x3d, 0xca, 0x42, 0x2f, 0x4e, 0xb8, 0xe0, 0x78, 0x67, 0x36, 0x48, 0x3d, 0xb9,
	0xc5, 0xcb, 0xf2, 0xd3, 0x23, 0xf7, 0x43, 0x89, 0x23, 0x8c, 0x71, 0x41, 0x44, 0xc4, 0x59, 0x2a,
	0x61, 0xa9, 0x20, 0x62, 0x92, 0x6a, 0x94, 0xfb, 0x9e, 0xdc, 0x10, 0xf2, 0x84, 0xca, 0x15, 0x3a,
	0x13, 0x94, 0xa5, 0x11, 0x67, 0x66, 0x71, 0x77, 0x99, 0x6a, 0x2a, 0x92, 0x88, 0x0d, 0xcd, 0x8e,
	0x77, 0xa7, 0x64, 0x14, 0x0d, 0x88, 0xa0, 0xed, 0x2c, 0xd0, 0x0b, 0xfb, 0xbf, 0x34, 0xa1, 0xda,
	0xd3, 0x20, 0xdc, 0x83, 0xba, 0xc1, 0xf7, 0x47, 0x51, 0x2a, 0x5a, 0x68, 0x17, 0x1d, 0x38, 0x87,
	0x07, 0xde, 0x92, 0x03, 0x7b, 0x06, 0x93, 0xfd, 0x7e, 0x13, 0xa5, 0xa2, 0x5b, 0x0a, 0x9c, 0xf1,
	0xe2, 0xb1, 0x48, 0x27, 0x12, 0x4a, 0x5b, 0xe5, 0xd5, 0xe9, 0x2e, 0x12, 0x4a, 0x0b, 0x74, 0xf2,
	0x11, 0x7f, 0x05, 0x0e, 0x67, 0x7d, 0xc6, 0xfb, 0x2a, 0xd9, 0xb2, 0x14, 0xdb, 0x47, 0x8f, 0xb2,
	0x7d, 0xc7, 0x54, 0x14, 0xd4, 0x38, 0xfb, 0x96, 0xab, 0xd0, 0xbd, 0x43, 0x50, 0x35, 0x69, 0x7c,
	0x0c, 0x55, 0x03, 0x32, 0xaf, 0xfa, 0xfe, 0x63, 0x6c, 0xdd, 0x52, 0x90, 0x6d, 0xc7, 0x9f, 0x41,
	0x85, 0x84, 0xb2, 0x51, 0xe6, 0xa5, 0xf6, 0x14, 0x50, 0xb6, 0x47, 0x02, 0x2e, 0xe6, 0x31, 0x1d,
	0x9c, 0x64, 0x3d, 0xfa, 0x92, 0xb3, 0xeb, 0x68, 0xd8, 0x2d, 0x05, 0x06, 0xe2, 0x37, 0xc0, 0xe6,
	0x4c, 0xbf, 0x05, 0xb6, 0x5e, 0xfa, 0xc8, 0xfd, 0xdb, 0x06, 0xa7, 0x50, 0x47, 0x7c, 0x09, 0xb6,
	0x11, 0x4a, 0x5b, 0x68, 0xd7, 0x3a, 0x70, 0x0e, 0x3f, 0x5d, 0xb5, 0x07, 0xde, 0x69, 0x44, 0x47,
	0x03, 0x93, 0xf0, 0xed, 0x57, 0xfe, 0xe6, 0x6f, 0xa8, 0x6c, 0xa3, 0x20, 0x27, 0x74, 0xef, 0x2a,
	0x50, 0x3b, 0x4b, 0xe8, 0x20, 0x0a, 0x89, 0xa0, 0x98, 0x43, 0x33, 0x8d, 0xd8, 0x70, 0x44, 0xfb,
	0x71, 0x96, 0x33, 0xb5, 0xf0, 0x57, 0x96, 0xcc, 0xd9, 0xbc, 0x73, 0x45, 0x95, 0x3f, 0x77, 0x4b,
	0x41, 0x23, 0xbd, 0x9f, 0xc2, 0x04, 0x80, 0x27, 0xfd, 0xac, 0xec, 0xba, 0x7a, 0x9f, 0xaf, 0x21,
	0x95, 0x47, 0xc6, 0x79, 0x35, 0x9e, 0x64, 0x36, 0x0e, 0xc1, 0x21, 0x6c, 0x90, 0x6b, 0x58, 0xcf,
	0xa6, 0x01, 0x84, 0x65, 0xa5, 0xc5, 0xdf, 0x83, 0xc3, 0xb8, 0xc8, 0x45, 0x36, 0x94, 0xc8, 0xe1,
	0xd3, 0x45, 0x24, 0x2d, 0xe3, 0xc2, 0xac, 0xb9, 0x2f, 0x10, 0x34, 0x1e, 0x54, 0x11, 0x7f, 0x01,
	0x9b, 0x11, 0x8b, 0x27, 0xd9, 0x3c, 0xbe, 0xd9, 0x6b, 0xaa, 0xef, 0xbf, 0xa2, 0x72, 0x13, 0x05,
	0x1a, 0x89, 0x4f, 0xc0, 0x99, 0x92, 0xd1, 0x84, 0x9a, 0xd9, 0xd1, 0x65, 0xdf, 0x5f, 0x7a, 0xda,
	0x73, 0x75, 0x6d, 0x2c, 0x3c, 0x0f, 0x0a, 0xa8, 0x07, 0xe6, 0x14, 0xea, 0xe1, 0x24, 0x15, 0x7c,
	0x7c, 0x6f, 0x06, 0x57, 0x32, 0xbf, 0xa3, 0x81, 0x8a, 0xc7, 0xdf, 0xce, 0x07, 0x4f, 0x0f, 0xc0,
	0x2d, 0x6c, 0xdd, 0xab, 0x35, 0xfe, 0x11, 0x6a, 0x45, 0x3f, 0x5a, 0xeb, 0xd5, 0x36, 0xf7, 0x7f,
	0x39, 0x58, 0xd0, 0xf9, 0xef, 0x00, 0x28, 0x82, 0xbe, 0xe4, 0xd2, 0xfa, 0x7f, 0x21, 0xa8, 0x17,
	0x07, 0xe7, 0xa1, 0x3e, 0x7a, 0x0b, 0x7d, 0xdd, 0x87, 0x05, 0x1d, 0xfe, 0x7a, 0x31, 0xfe, 0xa6,
	0x11, 0x2b, 0x5d, 0x62, 0x05, 0xb2, 0x2a, 0xd7, 0x29, 0xf7, 0xcf, 0x8d, 0xfc, 0xe2, 0x50, 0x57,
	0xe4, 0x33, 0x38, 0xe5, 0x12, 0x1a, 0x74, 0x46, 0x42, 0xe3, 0xec, 0xfe, 0x98, 0xc4, 0xe6, 0x90,
	0x9f, 0xac, 0x7a, 0x6f, 0xeb, 0xb8, 0x47, 0xe2, 0x6e, 0x29, 0xd8, 0x52, 0x5c, 0x59, 0x02, 0xff,
	0x0c, 0xcd, 0x38, 0xa1, 0xd7, 0xd1, 0xac, 0xc0, 0x6e, 0xad, 0xcf, 0xbe, 0xad, 0xc9, 0x72, 0xfa,
	0x87, 0xf6, 0xdc, 0x58, 0xcf, 0x9e, 0xee, 0x3f, 0x08, 0xec, 0x9c, 0xf4, 0x07, 0xb0, 0xe4, 0x31,
	0xb5, 0x09, 0x3b, 0x4f, 0x3e, 0xa6, 0xd7, 0x23, 0xf1, 0x09, 0x13, 0xc9, 0x5c, 0x95, 0xfa, 0x77,
	0x75, 0x19, 0x4b, 0x42, 0xf7, 0x27, 0xa9, 0xa1, 0x97, 0x70, 0x13, 0xac, 0x5b, 0x3a, 0x57, 0x5d,
	0xab, 0x05, 0x32, 0xc4, 0x1d, 0xd8, 0x54, 0x73, 0xf7, 0x14, 0x87, 0x04, 0x1a, 0xd2, 0x29, 0x1f,
	0x23, 0xbf, 0x09, 0x35, 0xf9, 0x9f, 0xbb, 0xf0, 0x78, 0xc7, 0xfe, 0xef, 0xdf, 0x3f, 0xfe, 0xaf,
	0x94, 0x6d, 0xe4, 0xef, 0x14, 0xfe, 0x97, 0xb3, 0x65, 0xff, 0x63, 0xf8, 0x20, 0xe4, 0x63, 0x6f,
	0x18, 0x89, 0x9b, 0xc9, 0xd5, 0x32, 0x35, 0xbf, 0x6e, 0xe4, 0xce, 0xe4, 0x77, 0xc3, 0x19, 0xba,
	0xaa, 0xa8, 0x0f, 0x88, 0xa3, 0xd7, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xc5, 0x2a, 0xf0, 0xf3,
	0x08, 0x00, 0x00,
}
