// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xds/type/matcher/v3/string.proto

package xds_type_matcher_v3

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringMatcher struct {
	// Types that are valid to be assigned to MatchPattern:
	//	*StringMatcher_Exact
	//	*StringMatcher_Prefix
	//	*StringMatcher_Suffix
	//	*StringMatcher_SafeRegex
	//	*StringMatcher_Contains
	MatchPattern         isStringMatcher_MatchPattern `protobuf_oneof:"match_pattern"`
	IgnoreCase           bool                         `protobuf:"varint,6,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *StringMatcher) Reset()         { *m = StringMatcher{} }
func (m *StringMatcher) String() string { return proto.CompactTextString(m) }
func (*StringMatcher) ProtoMessage()    {}
func (*StringMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a166c8eff2d056d, []int{0}
}

func (m *StringMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMatcher.Unmarshal(m, b)
}
func (m *StringMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMatcher.Marshal(b, m, deterministic)
}
func (m *StringMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMatcher.Merge(m, src)
}
func (m *StringMatcher) XXX_Size() int {
	return xxx_messageInfo_StringMatcher.Size(m)
}
func (m *StringMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_StringMatcher proto.InternalMessageInfo

type isStringMatcher_MatchPattern interface {
	isStringMatcher_MatchPattern()
}

type StringMatcher_Exact struct {
	Exact string `protobuf:"bytes,1,opt,name=exact,proto3,oneof"`
}

type StringMatcher_Prefix struct {
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3,oneof"`
}

type StringMatcher_Suffix struct {
	Suffix string `protobuf:"bytes,3,opt,name=suffix,proto3,oneof"`
}

type StringMatcher_SafeRegex struct {
	SafeRegex *RegexMatcher `protobuf:"bytes,5,opt,name=safe_regex,json=safeRegex,proto3,oneof"`
}

type StringMatcher_Contains struct {
	Contains string `protobuf:"bytes,7,opt,name=contains,proto3,oneof"`
}

func (*StringMatcher_Exact) isStringMatcher_MatchPattern() {}

func (*StringMatcher_Prefix) isStringMatcher_MatchPattern() {}

func (*StringMatcher_Suffix) isStringMatcher_MatchPattern() {}

func (*StringMatcher_SafeRegex) isStringMatcher_MatchPattern() {}

func (*StringMatcher_Contains) isStringMatcher_MatchPattern() {}

func (m *StringMatcher) GetMatchPattern() isStringMatcher_MatchPattern {
	if m != nil {
		return m.MatchPattern
	}
	return nil
}

func (m *StringMatcher) GetExact() string {
	if x, ok := m.GetMatchPattern().(*StringMatcher_Exact); ok {
		return x.Exact
	}
	return ""
}

func (m *StringMatcher) GetPrefix() string {
	if x, ok := m.GetMatchPattern().(*StringMatcher_Prefix); ok {
		return x.Prefix
	}
	return ""
}

func (m *StringMatcher) GetSuffix() string {
	if x, ok := m.GetMatchPattern().(*StringMatcher_Suffix); ok {
		return x.Suffix
	}
	return ""
}

func (m *StringMatcher) GetSafeRegex() *RegexMatcher {
	if x, ok := m.GetMatchPattern().(*StringMatcher_SafeRegex); ok {
		return x.SafeRegex
	}
	return nil
}

func (m *StringMatcher) GetContains() string {
	if x, ok := m.GetMatchPattern().(*StringMatcher_Contains); ok {
		return x.Contains
	}
	return ""
}

func (m *StringMatcher) GetIgnoreCase() bool {
	if m != nil {
		return m.IgnoreCase
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StringMatcher) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StringMatcher_Exact)(nil),
		(*StringMatcher_Prefix)(nil),
		(*StringMatcher_Suffix)(nil),
		(*StringMatcher_SafeRegex)(nil),
		(*StringMatcher_Contains)(nil),
	}
}

type ListStringMatcher struct {
	Patterns             []*StringMatcher `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListStringMatcher) Reset()         { *m = ListStringMatcher{} }
func (m *ListStringMatcher) String() string { return proto.CompactTextString(m) }
func (*ListStringMatcher) ProtoMessage()    {}
func (*ListStringMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a166c8eff2d056d, []int{1}
}

func (m *ListStringMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStringMatcher.Unmarshal(m, b)
}
func (m *ListStringMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStringMatcher.Marshal(b, m, deterministic)
}
func (m *ListStringMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStringMatcher.Merge(m, src)
}
func (m *ListStringMatcher) XXX_Size() int {
	return xxx_messageInfo_ListStringMatcher.Size(m)
}
func (m *ListStringMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStringMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_ListStringMatcher proto.InternalMessageInfo

func (m *ListStringMatcher) GetPatterns() []*StringMatcher {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func init() {
	proto.RegisterType((*StringMatcher)(nil), "xds.type.matcher.v3.StringMatcher")
	proto.RegisterType((*ListStringMatcher)(nil), "xds.type.matcher.v3.ListStringMatcher")
}

func init() { proto.RegisterFile("xds/type/matcher/v3/string.proto", fileDescriptor_8a166c8eff2d056d) }

var fileDescriptor_8a166c8eff2d056d = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4f, 0xc2, 0x30,
	0x1c, 0xc5, 0xe9, 0x10, 0x18, 0xff, 0x85, 0x44, 0xa7, 0xd1, 0x85, 0x0b, 0x03, 0x63, 0xb2, 0x53,
	0x97, 0x80, 0x9f, 0xa0, 0x5e, 0x38, 0x60, 0x42, 0xe6, 0xd9, 0x90, 0xb2, 0x95, 0xd1, 0x44, 0xb6,
	0xa5, 0x2d, 0x64, 0x7e, 0x05, 0x8f, 0xde, 0xfc, 0xa6, 0x86, 0x93, 0xe9, 0x3a, 0x49, 0xd0, 0xdd,
	0xb6, 0xbe, 0xdf, 0x7b, 0xff, 0xd7, 0xfe, 0xc1, 0x2f, 0x13, 0x19, 0xaa, 0xf7, 0x82, 0x85, 0x3b,
	0xaa, 0xe2, 0x2d, 0x13, 0xe1, 0x61, 0x16, 0x4a, 0x25, 0x78, 0x96, 0xe2, 0x42, 0xe4, 0x2a, 0x77,
	0xaf, 0xcb, 0x44, 0x62, 0x4d, 0xe0, 0x9a, 0xc0, 0x87, 0xd9, 0x70, 0xd4, 0x64, 0x13, 0x2c, 0x65,
	0xa5, 0x71, 0x0d, 0xef, 0x0e, 0xf4, 0x8d, 0x27, 0x54, 0xb1, 0xf0, 0xf7, 0xc3, 0x08, 0x93, 0x2f,
	0x0b, 0x06, 0x2f, 0x55, 0xfe, 0xb3, 0x71, 0xba, 0xb7, 0xd0, 0x61, 0x25, 0x8d, 0x95, 0x87, 0x7c,
	0x14, 0xf4, 0xe7, 0xad, 0xc8, 0xfc, 0xba, 0x63, 0xe8, 0x16, 0x82, 0x6d, 0x78, 0xe9, 0x59, 0x5a,
	0x20, 0xbd, 0x23, 0xb9, 0x10, 0xd6, 0x25, 0x9a, 0xb7, 0xa2, 0x5a, 0xd0, 0x88, 0xdc, 0x6f, 0x34,
	0xd2, 0xfe, 0x87, 0x18, 0xc1, 0x5d, 0x00, 0x48, 0xba, 0x61, 0xab, 0xaa, 0x9c, 0xd7, 0xf1, 0x51,
	0xe0, 0x4c, 0xc7, 0xb8, 0xe1, 0x4e, 0x38, 0xd2, 0x44, 0x5d, 0x8a, 0xd8, 0x47, 0xd2, 0xf9, 0x40,
	0x26, 0xaa, 0xaf, 0x03, 0x2a, 0xd5, 0x7d, 0x00, 0x3b, 0xce, 0x33, 0x45, 0x79, 0x26, 0xbd, 0xde,
	0xdf, 0x91, 0x27, 0xc9, 0x1d, 0x81, 0xc3, 0xd3, 0x2c, 0x17, 0x6c, 0x15, 0x53, 0xc9, 0xbc, 0xae,
	0x8f, 0x02, 0x3b, 0x02, 0x73, 0xf4, 0x44, 0x25, 0x23, 0x37, 0x30, 0xa8, 0x26, 0xaf, 0x0a, 0xaa,
	0x14, 0x13, 0x99, 0xdb, 0xfe, 0x26, 0x68, 0xf2, 0x0a, 0x57, 0x0b, 0x2e, 0xd5, 0xf9, 0xf3, 0xcc,
	0xc1, 0xae, 0x21, 0xe9, 0x21, 0xbf, 0x1d, 0x38, 0xd3, 0x49, 0x63, 0xfd, 0x33, 0x57, 0xd5, 0xff,
	0x13, 0x59, 0x36, 0x8a, 0x4e, 0x6e, 0xf2, 0x08, 0xf7, 0x71, 0xbe, 0xc3, 0x29, 0x57, 0xdb, 0xfd,
	0x1a, 0xef, 0x93, 0x82, 0x36, 0x05, 0x11, 0xc7, 0x24, 0x2d, 0xf5, 0xba, 0x96, 0x68, 0xdd, 0xad,
	0xf6, 0x36, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x95, 0x0b, 0xac, 0xb1, 0x2a, 0x02, 0x00, 0x00,
}
