# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xds/type/matcher/v3/regex.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'xds/type/matcher/v3/regex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fxds/type/matcher/v3/regex.proto\x12\x13xds.type.matcher.v3\x1a\x1b\x62uf/validate/validate.proto\"\x94\x01\n\x0cRegexMatcher\x12I\n\ngoogle_re2\x18\x01 \x01(\x0b\x32+.xds.type.matcher.v3.RegexMatcher.GoogleRE2B\x06\xbaH\x03\xc8\x01\x01H\x00\x12\x16\n\x05regex\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x1a\x0b\n\tGoogleRE2B\x14\n\x0b\x65ngine_type\x12\x05\xbaH\x02\x08\x01\x42Z\n\x1e\x63om.github.xds.type.matcher.v3B\nRegexProtoP\x01Z*github.com/cncf/xds/go/xds/type/matcher/v3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xds.type.matcher.v3.regex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.github.xds.type.matcher.v3B\nRegexProtoP\001Z*github.com/cncf/xds/go/xds/type/matcher/v3'
  _globals['_REGEXMATCHER'].oneofs_by_name['engine_type']._loaded_options = None
  _globals['_REGEXMATCHER'].oneofs_by_name['engine_type']._serialized_options = b'\272H\002\010\001'
  _globals['_REGEXMATCHER'].fields_by_name['google_re2']._loaded_options = None
  _globals['_REGEXMATCHER'].fields_by_name['google_re2']._serialized_options = b'\272H\003\310\001\001'
  _globals['_REGEXMATCHER'].fields_by_name['regex']._loaded_options = None
  _globals['_REGEXMATCHER'].fields_by_name['regex']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_REGEXMATCHER']._serialized_start=86
  _globals['_REGEXMATCHER']._serialized_end=234
  _globals['_REGEXMATCHER_GOOGLERE2']._serialized_start=201
  _globals['_REGEXMATCHER_GOOGLERE2']._serialized_end=212
# @@protoc_insertion_point(module_scope)
