// Code generated by protoc-gen-go. DO NOT EDIT.
// source: udpa/annotations/status.proto

package udpa_annotations

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PackageVersionStatus int32

const (
	PackageVersionStatus_UNKNOWN                      PackageVersionStatus = 0
	PackageVersionStatus_FROZEN                       PackageVersionStatus = 1
	PackageVersionStatus_ACTIVE                       PackageVersionStatus = 2
	PackageVersionStatus_NEXT_MAJOR_VERSION_CANDIDATE PackageVersionStatus = 3
)

var PackageVersionStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "FROZEN",
	2: "ACTIVE",
	3: "NEXT_MAJOR_VERSION_CANDIDATE",
}

var PackageVersionStatus_value = map[string]int32{
	"UNKNOWN":                      0,
	"FROZEN":                       1,
	"ACTIVE":                       2,
	"NEXT_MAJOR_VERSION_CANDIDATE": 3,
}

func (x PackageVersionStatus) String() string {
	return proto.EnumName(PackageVersionStatus_name, int32(x))
}

func (PackageVersionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_011cc2e7e491b0ff, []int{0}
}

type StatusAnnotation struct {
	WorkInProgress       bool                 `protobuf:"varint,1,opt,name=work_in_progress,json=workInProgress,proto3" json:"work_in_progress,omitempty"`
	PackageVersionStatus PackageVersionStatus `protobuf:"varint,2,opt,name=package_version_status,json=packageVersionStatus,proto3,enum=udpa.annotations.PackageVersionStatus" json:"package_version_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StatusAnnotation) Reset()         { *m = StatusAnnotation{} }
func (m *StatusAnnotation) String() string { return proto.CompactTextString(m) }
func (*StatusAnnotation) ProtoMessage()    {}
func (*StatusAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_011cc2e7e491b0ff, []int{0}
}

func (m *StatusAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusAnnotation.Unmarshal(m, b)
}
func (m *StatusAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusAnnotation.Marshal(b, m, deterministic)
}
func (m *StatusAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusAnnotation.Merge(m, src)
}
func (m *StatusAnnotation) XXX_Size() int {
	return xxx_messageInfo_StatusAnnotation.Size(m)
}
func (m *StatusAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_StatusAnnotation proto.InternalMessageInfo

func (m *StatusAnnotation) GetWorkInProgress() bool {
	if m != nil {
		return m.WorkInProgress
	}
	return false
}

func (m *StatusAnnotation) GetPackageVersionStatus() PackageVersionStatus {
	if m != nil {
		return m.PackageVersionStatus
	}
	return PackageVersionStatus_UNKNOWN
}

type MessageStatusAnnotation struct {
	WorkInProgress       bool     `protobuf:"varint,1,opt,name=work_in_progress,json=workInProgress,proto3" json:"work_in_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageStatusAnnotation) Reset()         { *m = MessageStatusAnnotation{} }
func (m *MessageStatusAnnotation) String() string { return proto.CompactTextString(m) }
func (*MessageStatusAnnotation) ProtoMessage()    {}
func (*MessageStatusAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_011cc2e7e491b0ff, []int{1}
}

func (m *MessageStatusAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageStatusAnnotation.Unmarshal(m, b)
}
func (m *MessageStatusAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageStatusAnnotation.Marshal(b, m, deterministic)
}
func (m *MessageStatusAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageStatusAnnotation.Merge(m, src)
}
func (m *MessageStatusAnnotation) XXX_Size() int {
	return xxx_messageInfo_MessageStatusAnnotation.Size(m)
}
func (m *MessageStatusAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageStatusAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_MessageStatusAnnotation proto.InternalMessageInfo

func (m *MessageStatusAnnotation) GetWorkInProgress() bool {
	if m != nil {
		return m.WorkInProgress
	}
	return false
}

type FieldStatusAnnotation struct {
	WorkInProgress       bool     `protobuf:"varint,1,opt,name=work_in_progress,json=workInProgress,proto3" json:"work_in_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldStatusAnnotation) Reset()         { *m = FieldStatusAnnotation{} }
func (m *FieldStatusAnnotation) String() string { return proto.CompactTextString(m) }
func (*FieldStatusAnnotation) ProtoMessage()    {}
func (*FieldStatusAnnotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_011cc2e7e491b0ff, []int{2}
}

func (m *FieldStatusAnnotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldStatusAnnotation.Unmarshal(m, b)
}
func (m *FieldStatusAnnotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldStatusAnnotation.Marshal(b, m, deterministic)
}
func (m *FieldStatusAnnotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldStatusAnnotation.Merge(m, src)
}
func (m *FieldStatusAnnotation) XXX_Size() int {
	return xxx_messageInfo_FieldStatusAnnotation.Size(m)
}
func (m *FieldStatusAnnotation) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldStatusAnnotation.DiscardUnknown(m)
}

var xxx_messageInfo_FieldStatusAnnotation proto.InternalMessageInfo

func (m *FieldStatusAnnotation) GetWorkInProgress() bool {
	if m != nil {
		return m.WorkInProgress
	}
	return false
}

var E_FileStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*StatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.file_status",
	Tag:           "bytes,222707719,opt,name=file_status",
	Filename:      "udpa/annotations/status.proto",
}

var E_MessageStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageStatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.message_status",
	Tag:           "bytes,222707719,opt,name=message_status",
	Filename:      "udpa/annotations/status.proto",
}

var E_FieldStatus = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldStatusAnnotation)(nil),
	Field:         222707719,
	Name:          "udpa.annotations.field_status",
	Tag:           "bytes,222707719,opt,name=field_status",
	Filename:      "udpa/annotations/status.proto",
}

func init() {
	proto.RegisterEnum("udpa.annotations.PackageVersionStatus", PackageVersionStatus_name, PackageVersionStatus_value)
	proto.RegisterType((*StatusAnnotation)(nil), "udpa.annotations.StatusAnnotation")
	proto.RegisterType((*MessageStatusAnnotation)(nil), "udpa.annotations.MessageStatusAnnotation")
	proto.RegisterType((*FieldStatusAnnotation)(nil), "udpa.annotations.FieldStatusAnnotation")
	proto.RegisterExtension(E_FileStatus)
	proto.RegisterExtension(E_MessageStatus)
	proto.RegisterExtension(E_FieldStatus)
}

func init() { proto.RegisterFile("udpa/annotations/status.proto", fileDescriptor_011cc2e7e491b0ff) }

var fileDescriptor_011cc2e7e491b0ff = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x6f, 0xa2, 0x40,
	0x18, 0xc5, 0x17, 0x37, 0x71, 0x37, 0x1f, 0xbb, 0x86, 0x10, 0x77, 0xd7, 0x6c, 0x34, 0x25, 0x1c,
	0x5a, 0xda, 0x03, 0x24, 0xf6, 0xe6, 0x8d, 0x28, 0x26, 0xb4, 0x11, 0xcc, 0x68, 0x6d, 0xd3, 0xb4,
	0x21, 0x28, 0x03, 0xa1, 0x22, 0x43, 0x18, 0x6c, 0xaf, 0xbd, 0xf5, 0x6f, 0x68, 0xff, 0xda, 0x06,
	0x46, 0x5b, 0x23, 0xf4, 0xe2, 0x6d, 0xf2, 0xbe, 0x99, 0xef, 0xf7, 0xe6, 0x3d, 0xe8, 0xac, 0xbd,
	0xc4, 0xd5, 0xdc, 0x38, 0x26, 0x99, 0x9b, 0x85, 0x24, 0xa6, 0x1a, 0xcd, 0xdc, 0x6c, 0x4d, 0xd5,
	0x24, 0x25, 0x19, 0x11, 0x85, 0x7c, 0xac, 0xee, 0x8c, 0xff, 0x4b, 0x01, 0x21, 0x41, 0x84, 0xb5,
	0x62, 0x3e, 0x5f, 0xfb, 0x9a, 0x87, 0xe9, 0x22, 0x0d, 0x93, 0x8c, 0xa4, 0xec, 0x8d, 0xfc, 0xc6,
	0x81, 0x30, 0x29, 0x96, 0xe8, 0x1f, 0xef, 0x44, 0x05, 0x84, 0x27, 0x92, 0x2e, 0x9d, 0x30, 0x76,
	0x92, 0x94, 0x04, 0x29, 0xa6, 0xb4, 0xc5, 0x49, 0x9c, 0xf2, 0x13, 0x35, 0x72, 0xdd, 0x8c, 0xc7,
	0x1b, 0x55, 0xbc, 0x83, 0xbf, 0x89, 0xbb, 0x58, 0xba, 0x01, 0x76, 0x1e, 0x71, 0x4a, 0x43, 0x12,
	0x3b, 0xcc, 0x52, 0xab, 0x26, 0x71, 0x4a, 0xa3, 0x7b, 0xac, 0xee, 0x7b, 0x52, 0xc7, 0xec, 0xfe,
	0x8c, 0x5d, 0x67, 0x6c, 0xd4, 0x4c, 0x2a, 0x54, 0xb9, 0x0f, 0xff, 0x46, 0x98, 0x52, 0x37, 0xc0,
	0x87, 0x5b, 0x94, 0x75, 0xf8, 0x33, 0x0c, 0x71, 0xe4, 0x1d, 0xbe, 0xe2, 0xec, 0x1e, 0x9a, 0x55,
	0xae, 0x45, 0x1e, 0x7e, 0x5c, 0x59, 0x97, 0x96, 0x7d, 0x6d, 0x09, 0xdf, 0x44, 0x80, 0xfa, 0x10,
	0xd9, 0xb7, 0x86, 0x25, 0x70, 0xf9, 0x59, 0xef, 0x4f, 0xcd, 0x99, 0x21, 0xd4, 0x44, 0x09, 0xda,
	0x96, 0x71, 0x33, 0x75, 0x46, 0xfa, 0x85, 0x8d, 0x9c, 0x99, 0x81, 0x26, 0xa6, 0x6d, 0x39, 0x7d,
	0xdd, 0x1a, 0x98, 0x03, 0x7d, 0x6a, 0x08, 0xdf, 0x7b, 0x1e, 0xf0, 0x7e, 0x18, 0xe1, 0x4d, 0x72,
	0x62, 0x5b, 0x65, 0xad, 0xa9, 0xdb, 0xd6, 0xd4, 0x61, 0x18, 0x61, 0x3b, 0x29, 0xe2, 0x6b, 0xbd,
	0x3c, 0xbf, 0x3e, 0x48, 0x9c, 0xc2, 0x77, 0xe5, 0x72, 0xb4, 0xfb, 0x5f, 0x44, 0x90, 0xef, 0x65,
	0x6a, 0x2f, 0x83, 0xc6, 0x8a, 0x85, 0xb9, 0x05, 0x1d, 0x95, 0x40, 0x9b, 0xb4, 0x4b, 0xac, 0xd3,
	0x32, 0xeb, 0x8b, 0x62, 0xd0, 0xef, 0xd5, 0xee, 0xa0, 0x17, 0xc1, 0x2f, 0x3f, 0x4f, 0x7f, 0xcb,
	0xec, 0x54, 0x7c, 0x0e, 0x47, 0x5e, 0x89, 0x78, 0x52, 0x26, 0x56, 0xb6, 0x88, 0x78, 0xff, 0x53,
	0x9e, 0xd7, 0x8b, 0xad, 0xe7, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x2b, 0x3d, 0xee, 0x29,
	0x03, 0x00, 0x00,
}
