trigger:
  branches:
    include:
    - 'main'
  tags:
    include:
    - 'v*'

jobs:
- job: CI
  pool:
    vmImage: 'ubuntu-latest'
  container: envoyproxy/envoy-build-ubuntu@sha256:b4fe088084579339ae8f7a44af899bbebd86a290af56e5ab7cc85ca99a09499c
  steps:
  - task: CacheBeta@1
    inputs:
      key: './WORKSPACE | ./.bazel* | **/*.bzl | ./MODULE.bazel'
      path: $(Agent.TempDirectory)/tmp

  # Install buf CLI for protobuf generation
  - bash: |
      curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.46.0/buf-Linux-x86_64" -o buf
      chmod +x buf
      sudo mv buf /usr/local/bin/
    displayName: 'Install Buf CLI'

  - bash: ci/check.sh
    env:
      TEST_TMPDIR: $(Agent.TempDirectory)/tmp

  - bash: tools/buf_generate.sh && test -z "$(git status --porcelain)"
    env:
      TEST_TMPDIR: $(Agent.TempDirectory)/tmp

- job: go_build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: GoTool@0
    displayName: "Install Go"
    inputs:
      version: '1.20.2'

  - task: Go@0
    displayName: "go mod download"
    inputs:
      command: 'custom'
      customCommand: 'mod'
      arguments: 'download'
      workingDirectory: 'go/'

  - task: Go@0
    displayName: "go mod verify"
    inputs:
      command: 'custom'
      customCommand: 'mod'
      arguments: 'verify'
      workingDirectory: 'go/'

  - task: Go@0
    displayName: "go build ./..."
    inputs:
      command: 'build'
      arguments: '-v ./...'
      workingDirectory: 'go/'
